import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./styles/globals.css";


export const metadata = {
  title: "Yukta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
